INDEPENDENT_VARIABLES: [SEED, NUM_POINTS, PLANNER_TYPE, FAILURE_RISK]
SAVE_PATHS: true

SEED: [77, 0, 1, 2]
NUM_POINTS: [25, 50, 75, 100]

PLANNER_TYPE: [OurPlannerStochastic]
ENVIRONMENT: ../env_settings.yaml
TSP_LOCAL_SEARCH: false
FAILURE_RISK: [0.5, 0.2, 0.1, 0.05, 0.02, 0.01]

START_POINT: [0, 0]
END_POINT: [4000, 4000]
DUMMY_POINT: [4000, 0]
SPACE_SIZE: 4000
FIXED_Z: 500

TAKEOFF_LANDING_TIME: 100.0
UAV_BATTERY_TIME: 600.0
CHARGE_RATE: 1

KSI: 0.001
