INDEPENDENT_VARIABLES: [SEED, NUM_POINTS, PLANNER_TYPE, UAV_DELTA_TIME]
SAVE_PATHS: true

SEED: [77, 0, 1, 2]
NUM_POINTS: [25, 50]

PLANNER_TYPE: [OurPlannerDeterministic]
ENVIRONMENT: ../env_settings.yaml
TSP_LOCAL_SEARCH: false
UAV_DELTA_TIME: [0, 10, 20, 50, 100, 200]
UGV_DELTA_TIME: 0

START_POINT: [0, 0]
END_POINT: [4000, 4000]
SPACE_SIZE: 4000
FIXED_Z: 500

TAKEOFF_LANDING_TIME: 100.0
UAV_BATTERY_TIME: 600.0
CHARGE_RATE: 1

KSI: 0.001
