INDEPENDENT_VARIABLES: [SEED, NUM_POINTS, PLANNER_TYPE]
SAVE_PATHS: true

SEED: [77]
NUM_POINTS: [25]

PLANNER_TYPE: [OurPlannerDeterministic]
ENVIRONMENT: env_settings.yaml
TSP_LOCAL_SEARCH: false

START_POINT: [0, 0]
END_POINT: [4000, 4000]
DUMMY_POINT: [4000, 0]
SPACE_SIZE: 4000
FIXED_Z: 500

UAV_SPEED: 10.0
UGV_SPEED: 2.5
TAKEOFF_LANDING_TIME: 100.0
UAV_BATTERY_TIME: 600.0
CHARGE_RATE: 1

KSI: 0.001
