INDEPENDENT_VARIABLES: [PLANNER_TYPE]
SAVE_PATHS: true

SEED: 0
NUM_POINTS: 25

PLANNER_TYPE: [OurPlannerDeterministic, OurPlannerStochastic]
ENVIRONMENT:
  TYPE: SplitEnvironment
  AGENT_ENVIRONMENTS:
    UAV:
      TYPE: GaussianEnvironment
      WEIGHT: 0.1
      WEIGHT_STD_DEV: 0.01
    UGV:
      TYPE: GaussianEnvironment
      WEIGHT: 0.4
      WEIGHT_STD_DEV: 0.05
TSP_LOCAL_SEARCH: false
UAV_DELTA_TIME: 0
UGV_DELTA_TIME: 0
FAILURE_RISK: 0.5

START_POINT: [0, 0]
END_POINT: [4000, 4000]
DUMMY_POINT: [4000, 0]
SPACE_SIZE: 4000
FIXED_Z: 500

TAKEOFF_LANDING_TIME: 100.0
UAV_BATTERY_TIME: 600.0
CHARGE_RATE: 1

KSI: 0.001
