
POINTS:
  TYPE: Uniform
  SPACE_SIZE: 2000
  FIXED_Z: 500

PLANNER:
  # PLANNER_TYPE: [OurPlannerDeterministic, OurPlannerStochastic]
  TSP_LOCAL_SEARCH: false
  # UAV_DELTA_TIME: 0
  # UGV_DELTA_TIME: 0
  FAILURE_RISK: 0.5

  ENVIRONMENT:
    TYPE: SplitEnvironment
    AGENT_ENVIRONMENTS:
      UAV:
        TYPE: GaussianEnvironment
        WEIGHT: 0.1
        WEIGHT_STD_DEV: 0.01
      UGV:
        TYPE: GaussianEnvironment
        WEIGHT: 0.4
        WEIGHT_STD_DEV: 0.05

START_POINT: [0, 0]
END_POINT: [2000, 2000]
