
# PLANNER_TYPE: [OurPlannerDeterministic, OurPlannerStochastic]
TSP_LOCAL_SEARCH: false
# UAV_DELTA_TIME: 0
# UGV_DELTA_TIME: 0
FAILURE_RISK: 0.5

START_POINT: [0, 0]
END_POINT: [2000, 2000]
DUMMY_POINT: [2000, 0]
SPACE_SIZE: 2000
FIXED_Z: 500
