INDEPENDENT_VARIABLES: [SEED, POINTS.NUM_POINTS, PLANNER.TYPE, PLANNER.FAILURE_RISK]
SAVE_PATHS: true

SEED: [0]

POINTS:
  TYPE: Uniform
  NUM_POINTS: [25, 50, 75, 100]
  SPACE_SIZE: 4000
  FIXED_Z: 500

PLANNER:
  TYPE: [OurPlannerStochastic]
  ENVIRONMENT: $../env_settings.yaml
  TSP_LOCAL_SEARCH: false
  FAILURE_RISK: [0.5, 0.2, 0.1, 0.05, 0.02, 0.01]
  REFINE_TOURS: true
  TAKEOFF_LANDING_TIME: 100.0
  UAV_BATTERY_TIME: 600.0
  CHARGE_RATE: 1
  KSI: 0.001
  PARALLEL_DP: True

START_POINT: [0, 0]
END_POINT: [4000, 4000]
