
POINTS:
  TYPE: Uniform
  SPACE_SIZE: 2000
  FIXED_Z: 500

PLANNER:
  TYPE: OurPlannerStochastic
  TSP_LOCAL_SEARCH: false
  FAILURE_RISK: 0.5
  TAKEOFF_LANDING_TIME: 100.0
  UAV_BATTERY_TIME: 300.0
  CHARGE_RATE: 1
  PARALLEL_DP: False

  ENVIRONMENT: $env_settings.yaml

START_POINT: [0, 0]
END_POINT: [2000, 2000]
