# INDEPENDENT_VARIABLES: [ONLINE_PLANNER]

SEED: 0
NUM_RUNS: 50
ENVIRONMENT: $../env_settings.yaml

ONLINE_PLANNER:
  # FREQUENCY: UavPoints
  HORIZON_TOURS: 2

  TYPE: OurOnlinePlanner
  ENVIRONMENT: $../env_settings.yaml

  TSP_LOCAL_SEARCH: false
  FAILURE_RISK: 0.1
  REFINE_TOURS: false
  PARALLEL_DP: false
  REQUIRE_FEASIBLE: true

  TAKEOFF_LANDING_TIME: 100.0
  UAV_BATTERY_TIME: 600.0
  CHARGE_RATE: 1
