INDEPENDENT_VARIABLES: [SEED, POINTS.NUM_POINTS, PLANNER.TYPE, PLANNER.FAILURE_RISK]
SAVE_PATHS: true

SEED: [77, 0, 1, 2]

POINTS:
  TYPE: Uniform
  NUM_POINTS: [25, 50]
  SPACE_SIZE: 4000
  FIXED_Z: 500

PLANNER:
  TYPE: [OurPlannerStochastic]
  ENVIRONMENT: $../env_settings.yaml
  TSP_LOCAL_SEARCH: false
  FAILURE_RISK: [0.1]
  REFINE_TOURS: false
  TAKEOFF_LANDING_TIME: 100.0
  UAV_BATTERY_TIME: 600.0
  CHARGE_RATE: 1
  PARALLEL_DP: True

START_POINT: [0, 0]
END_POINT: [4000, 4000]
