TYPE: OurOnlinePlanner
HORIZON_TOURS: 2

ENVIRONMENT: $env_settings.yaml

TSP_LOCAL_SEARCH: false
FAILURE_RISK: 0.1
REFINE_TOURS: true
PARALLEL_DP: false

TAKEOFF_LANDING_TIME: 100.0
UAV_BATTERY_TIME: 600.0
CHARGE_RATE: 1